version: '3.3'
services:
    nginx:
        volumes:
            - type: bind
              source: "/home/fulloa-s/data"
              target: "/var/www/html/"
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - 443:443
        depends_on:
            - php
            - mariadb
        restart: unless-stopped
        networks:
            - ulloanet

    php:
        volumes:
            - type: bind
              source: "/home/fulloa-s/data"
              target: "/var/www/html/"
        container_name: php
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WP_USER_LOGIN_AD: ${WP_USER_LOGIN_AD}
            WP_USER_PASS_AD: ${WP_USER_PASS_AD}
            WP_USER_EMAIL_AD: ${WP_USER_EMAIL_AD}
            WP_USER_LOGIN_U: ${WP_USER_LOGIN_U}
            WP_USER_PASS_U: ${WP_USER_PASS_U}
            WP_USER_EMAIL_U: ${WP_USER_EMAIL_U}
        tty: true
        expose:
            - 9000
        restart: unless-stopped
        depends_on:
            - mariadb
            - redis
            - vsftpd
        networks:
            - ulloanet

    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            DB_ROOT_PASS: ${DB_ROOT_PASS}
        tty: true
        volumes:
            - type: bind
              source: "/home/fulloa-s/data/mariadb"
              target: "/mariadb"
        expose:
            - 3306
        restart: unless-stopped
        networks:
            - ulloanet
    redis:
        container_name: redis
        build:
            context: ./requirements/bonus/redis
            dockerfile: Dockerfile
        tty: true
        expose:
            - 6379
        restart: unless-stopped
        networks:
            - ulloanet
    vsftpd:
        container_name: vsftpd
        build:
            context: ./requirements/bonus/vsftpd
            dockerfile: Dockerfile
        tty: true
        volumes:
            - type: bind
              source: "/home/fulloa-s/data"
              target: "/var/www/html/wordpress"
        expose:
            - 20
        restart: unless-stopped
        networks:
            - ulloanet
    ftp_client:
        container_name: ftp_client
        build:
            context: ./requirements/bonus/ftp_client
            dockerfile: Dockerfile
        tty: true
        expose:
            - 20
        restart: unless-stopped
        networks:
            - ulloanet

volumes:
    php:
     driver: local
     driver_opts:
      type: none
      o: bind
      device: "/home/fulloa-s/data"
    vsftpd:
     driver: local
     driver_opts:
      type: none
      o: bind
      device: "/home/fulloa-s/data"
    nginx:
     driver: local
     driver_opts:
      type: none
      o: bind
      device: "/home/fulloa-s/data"
    mariadb:
     driver: local
     driver_opts:
      type: none
      o: bind
      device: "/home/fulloa-s/data/mariadb"
      
networks:
    ulloanet:
        driver: bridge
